[project]
name = "inpainting-works"
description = "ğŸ”·Go to the top menu>Workflow>Browse TemplatesğŸ”·. This is a collection of my Inpainting workflows for Flux (expanded and COMPACT) + others. Previously called: 'Proper Flux Control-Net inpainting and/or outpainting with batch size - Alimama or Flux Fill'. By installing this 'node' you can always keep them up to date by updating on the manager. This is not a new custom node. You will still need to install all other custom nodes used on the workflows. It has all these features: Flux Dev with Alimama ğŸ”· Batches ğŸ”· Flux Fill ğŸ”· Flux Tool Loras: Depth or Canny ğŸ”· Mask grow with blur ğŸ”· Mask Aura ğŸ”· Outpainting ğŸ”· LoRA support ğŸ”· Localized Area Inpainting ğŸ”· Daemon Detailer ğŸ”· Fast Fill (like Auto1111 Fill) ğŸ”· Negative Thresholding ğŸ”· Loops ğŸ”· Prompt Scheduling ğŸ”· LoRA Scheduling ğŸ”· Original Image Resize ğŸ”· Compositing ğŸ”· Keep Original Metadata ğŸ”· Save Metadata / CivitAI Metadata. You will also find my 'Flux LoRA Block Weights Preset Tester' here as well."
version = "8.1.2"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/diodiogod/Comfy-Inpainting-Works"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "diogod"
DisplayName = "Comfy Inpainting Works"
Icon = "https://github.com/diodiogod/Comfy-Inpainting-Works/blob/main/images/logo.png"
includes = []
